### ISSUE TITLE
Core + Framwork

### ISSUE THREAD

**Issue by neumantm** [AmyAssist/Amy#17]
As a customer I want, that the system has a framwork and a core and that plugins can be loaded into the framework, so that the application is easy to expand.

60SP
Tasks:
- [x] Interface for plugins #18 
- [x] Ability to load plugins #20 
- [x] Implementation of the framework #26 
- [x] Implementation of the core components #23
