### ISSUE TITLE
Spotify player control

### ISSUE THREAD

**Issue by buddy200** [AmyAssist/Amy#29]
As a  customer i want a possibilty to control a spotify client or search for music titles or albums.

SP: 13

Tasks:
- [x] Web UI #28 
- [x] Authorization for Web API #32 
- [x] pause / skip / pause #37 
- [x] play #36 
- [x] search for albums, tracks, etc #38 
- [x] volume control #39 
- [x] device selection #40 
- [x] REST interface #50
