### ISSUE TITLE
Alarm feature

### ISSUE THREAD

**Issue by Bensge** [AmyAssist/Amy#3]
As a customer i want create a timer or alarm with my voice and stop it  

- [x] Create a timer or alarm using audio #5 
- [x] Save alarm and trigger alarm sound #12 
- [x] Stop a alarm or timer that's currently going off using audio #14 
- [x] Text parsing for timer feature #15 
- [x] Web UI for alarm / timer #16 

8SP
