### ISSUE TITLE
weather feature

### ISSUE THREAD

**Issue by Bensge** [AmyAssist/Amy#6]
- [x] get current weather using audio #10
- [ ] ~~get weather forecast (tomorrow, weekend) for a hardcoded location #11~~
- [x] weather UI for web interface #13

DoD: get weather for today, tomorrow, weekend. Should include precipitation probability, temperature, location.

5SP

**Comment by Bensge** [comment]
Done: 1a80d31cd598e5bf12e711213df0397483fdefba
