### ISSUE TITLE
Prevent Amy from listening when she is talking or music is playing

### ISSUE THREAD

**Issue by sinpat** [AmyAssist/Amy#66]
As a customer I don't want Amy to listen for voice commands, when she is talking or when music or other audio is playing, but I still want to be able to make her stop talking if I wish.

8 SP

Tasks:
- [x] Prevent speech recognition when Amy is talking #67
- [x] Prevent speech recognition when Amy is playing music or sounds #68
- [x] Make it possible to say "Amy shut up" #69 
- [ ] ~~Pause / turn down music when Amy wakes up~~ (Issue: #203 )

**Comment by Legion2** [comment]
if we prevent speech recognition when playing music then Amy never can wake up

**Comment by MakinZeel** [comment]
My latest Information:
We dont Prevent Amy from listening while music is Playing, but only the "Amy wake up" Command is active... is amy acrtivated we notify the System to turn down Volume, so that there won't be misheard commands from the music. Is Amy send inactive, we also send a notification that the volume can be turned loud again.

**Comment by Bensge** [comment]
@MakinZeel what‘s the status on this Issue? Do you need help?
