### ISSUE TITLE
Improving existing functionalities

### ISSUE THREAD

**Issue by sinpat** [AmyAssist/Amy#73]
20 SP

Tasks:
- [x] Ability to reactivate alarms #74 
- [x] Give back the actual time left of a timer #75 
- [x] Make it possible to set timers with seconds and hours #76 
- [x] Give the weather in the web UI a better look #77 
- [x] Provide Playlists of the used account on spotify #78 
- [x] Provide the most popular playlists on spotify #79 
- [x] Stop alarm sound immediately when timer is cancelled #96
- [x] Systemtime: Format date in a human (Amy TTS) readable string (5th of March blah) #93

**Comment by FlxB2** [comment]
(Web Ui Pr)[https://github.com/AmyAssist/Amy-Web/pull/29]
