### ISSUE TITLE
Spotify improvements

### ISSUE THREAD

**Issue by Bensge** [AmyAssist/Amy#83]
As a user/customer I want the Spotify plugin to recognize smart names like Smartphone, Computer, Laptop and in addition I want to have the ability to give my Spotify devices custom names which Amy understands

13 SP

Tasks:
- [x] Rename audio devices in WebApp (persist mappings) #97
<del>- [ ] use configured names with voice (dynamic SR grammar) #98</del>
- [x] Seamless transition of audio devices via Amy ("play on Laptop", "play in kitchen") #100
- [x] Select playlist from my liked playlists (by index)  #103
- [x] Display my featured playlist on the web app #101
- [x] possibility in Playerlogic to rename device and switch the deivce with this name #184
